#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "44.201.230.247"
  dns_config "$1" "44.201.230.247"
  dns_config "$1" "54.84.15.122"
  dns_config "$1" "3.87.208.156"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
