#!/usr/bin/env bash
# Bash script to display subdomain information

dns_config () {
    case "$2" in
        www)
            ip="54.210.47.110"
            ;;
        lb-01)
            ip="54.210.47.110"
            ;;
        web-01)
            ip="34.198.248.145"
            ;;
        web-02)
            ip="54.89.38.100"
            ;;
        *)
            ip="Not found"
            ;;
    esac
    echo "The subdomain $2 is a A record and points to $ip"
}

if [ "$#" -eq 1 ]; then
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    dns_config "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
